cmake_minimum_required(VERSION 3.20)
# Run without configuring the application or installing its dependencies:
# cmake -DSTUDIO_SOURCE_OUTPUT=/path/to/new/tree -P package_source.cmake
include("${CMAKE_CURRENT_LIST_DIR}/source_files.cmake")
if(NOT DEFINED STUDIO_SOURCE_OUTPUT OR STUDIO_SOURCE_OUTPUT STREQUAL "")
  message(FATAL_ERROR "Set STUDIO_SOURCE_OUTPUT to a new directory for the source distribution.")
endif()
get_filename_component(STUDIO_SOURCE_OUTPUT "${STUDIO_SOURCE_OUTPUT}" ABSOLUTE)
if(EXISTS "${STUDIO_SOURCE_OUTPUT}" OR IS_SYMLINK "${STUDIO_SOURCE_OUTPUT}")
  message(FATAL_ERROR "Refusing to overwrite existing output: ${STUDIO_SOURCE_OUTPUT}")
endif()
if(STUDIO_SOURCE_ZIP)
  if(EXISTS "${STUDIO_SOURCE_OUTPUT}.zip" OR IS_SYMLINK "${STUDIO_SOURCE_OUTPUT}.zip")
    message(FATAL_ERROR "Refusing to overwrite existing archive: ${STUDIO_SOURCE_OUTPUT}.zip")
  endif()
endif()

# Validate the entire manifest before creating output.
foreach(file IN LISTS STUDIO_SHARED_FILES)
  if(NOT EXISTS "${STUDIO_SOURCE_ROOT}/${file}" OR IS_DIRECTORY "${STUDIO_SOURCE_ROOT}/${file}")
    message(FATAL_ERROR "Missing source distribution input: ${STUDIO_SOURCE_ROOT}/${file}")
  endif()
endforeach()
foreach(file IN LISTS STUDIO_LOCAL_FILES)
  if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/${file}" OR IS_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/${file}")
    message(FATAL_ERROR "Missing source distribution input: ${CMAKE_CURRENT_LIST_DIR}/${file}")
  endif()
endforeach()
foreach(file IN LISTS STUDIO_SHARED_FILES)
  configure_file("${STUDIO_SOURCE_ROOT}/${file}" "${STUDIO_SOURCE_OUTPUT}/${file}" COPYONLY)
endforeach()
foreach(file IN LISTS STUDIO_LOCAL_FILES)
  configure_file("${CMAKE_CURRENT_LIST_DIR}/${file}" "${STUDIO_SOURCE_OUTPUT}/${file}" COPYONLY)
endforeach()
# GLAD expects this include spelling. Bundle our existing Khronos header rather
# than requiring a separate OpenGL development package in the exported tree.
configure_file("${SRC}/deps/misc/khrplatform.h"
  "${STUDIO_SOURCE_OUTPUT}/src/deps/misc/KHR/khrplatform.h" COPYONLY)
message(STATUS "Shader Studio source tree: ${STUDIO_SOURCE_OUTPUT}")
if(STUDIO_SOURCE_ZIP)
  get_filename_component(parent "${STUDIO_SOURCE_OUTPUT}" DIRECTORY)
  get_filename_component(name "${STUDIO_SOURCE_OUTPUT}" NAME)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${STUDIO_SOURCE_OUTPUT}.zip" --format=zip -- "${name}"
    WORKING_DIRECTORY "${parent}" RESULT_VARIABLE archive_result)
  if(NOT archive_result EQUAL 0)
    message(FATAL_ERROR "Could not create source archive (${archive_result}); the source tree is available above.")
  endif()
  message(STATUS "Shader Studio source archive: ${STUDIO_SOURCE_OUTPUT}.zip")
endif()
