# Require the archive, not the MinGW .dll.a import library. Resolve pkg-config's
# private dependencies to archives too, keeping curl's support DLLs out of Studio.
add_library(studio-curl INTERFACE)
if(MSVC)
  find_package(CURL 8.2 CONFIG REQUIRED)
  if(NOT TARGET CURL::libcurl_static)
    message(FATAL_ERROR "Shader Studio requires CURL::libcurl_static; install a static libcurl package.")
  endif()
  target_link_libraries(studio-curl INTERFACE CURL::libcurl_static)
else()
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(STUDIO_CURL REQUIRED libcurl>=8.2)
  set(_studio_saved_suffixes ${CMAKE_FIND_LIBRARY_SUFFIXES})
  set(CMAKE_FIND_LIBRARY_SUFFIXES .a)
  foreach(_library IN LISTS STUDIO_CURL_STATIC_LIBRARIES)
    unset(_studio_archive CACHE)
    find_library(_studio_archive NAMES ${_library} HINTS ${STUDIO_CURL_STATIC_LIBRARY_DIRS} REQUIRED)
    if(_studio_archive MATCHES "\\.dll\\.a$")
      message(FATAL_ERROR "A static archive is required for ${_library}: ${_studio_archive}")
    endif()
    target_link_libraries(studio-curl INTERFACE "${_studio_archive}")
  endforeach()
  unset(_studio_archive CACHE)
  set(CMAKE_FIND_LIBRARY_SUFFIXES ${_studio_saved_suffixes})
  target_include_directories(studio-curl INTERFACE ${STUDIO_CURL_INCLUDE_DIRS})
  target_compile_options(studio-curl INTERFACE ${STUDIO_CURL_STATIC_CFLAGS_OTHER})
  target_link_options(studio-curl INTERFACE ${STUDIO_CURL_STATIC_LDFLAGS_OTHER})
endif()
target_compile_definitions(studio-curl INTERFACE CURL_STATICLIB)
